import{a as B,S as E,i as a}from"./assets/vendor-CrlV4O_2.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))s(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(o){if(o.ep)return;o.ep=!0;const r=n(o);fetch(o.href,r)}})();const H="50290691-d51719558e36c91c48babc26d",M="https://pixabay.com/api/",$=15;async function A(t,e=1){console.log("Виклик функції getImagesByQuery із запитом:",t,e);const n={key:H,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:$,page:e};try{return(await B.get(M,{params:n})).data}catch(s){throw s}}const h=document.querySelector(".gallery"),p=document.querySelector(".select");document.querySelector(".loader");let d=null;function m(t){console.log("Виклик createGallery. Масив зображень:",t);try{const e=t.map(({webformatURL:n,largeImageURL:s,tags:o,likes:r,views:i,comments:q,downloads:P})=>(console.log("Обробка зображення:",{webformatURL:n,largeImageURL:s,tags:o}),`
        <li class="gallery-item">
          <a href="${s}" class="gallery-link">
          <img src="${n}" alt="${o}" loading="lazy" />
          </a>
        <div class="info">
        <p><b>Likes:</b> ${r}</p>
        <p><b>Views:</b> ${i}</p>
        <p><b>Comments:</b> ${q}</p>
        <p><b>Downloads:</b> ${P}</p>
      </div>
    </li>`)).join("");h.insertAdjacentHTML("beforeend",e),d?d.refresh():d=new E(".gallery a",{captionsData:"alt",captionDelay:250}),h.children.length>0&&p.classList.remove("is-hidden")}catch(e){throw console.error("Помилка у createGallery:",e),e}}function f(){try{h.innerHTML="",g(),console.log("Галерея очищена.")}catch(t){throw console.error("Помилка у функції clearGallery:",t),new Error("Не вдалося очистити галерею.")}}function x(){try{p.classList.remove("is-hidden")}catch(t){throw console.error("Помилка при показі кнопки Load more:",t),t}}function g(){try{p.classList.add("is-hidden")}catch(t){throw console.error("Помилка при приховуванні кнопки Load more:",t),t}}const L=document.querySelector(".form"),w=L.querySelector('input[name="search-text"]'),u=document.querySelector(".loader"),G=document.querySelector(".select"),b=document.querySelector(".gallery");let v="",l=1,c=0,y=!1;function O(){u&&(u.style.display="block"),console.log('Loader показано: видимість встановлена на "block".')}function R(){u&&(u.style.display="none"),console.log('Loader сховано: видимість встановлена на "none".')}async function I(t){return new Promise(e=>setTimeout(e,t))}async function S(t=!1){if(y){console.log("Запит уже виконується, новий запит не запускається.");return}y=!0,O(),g();try{await I(2e3);const e=await A(v,l);if(!e||!Array.isArray(e.hits))throw new Error("Невалідна структура відповіді API");if(e.hits.length===0){f(),a.info({title:"Нічого не знайдено",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}if(t&&(f(),c=e.totalHits,a.success({title:"Успіх",message:`Знайдено ${c} зображень.`,position:"topRight"})),m(e.hits),m(e.hits),t)window.scrollTo({top:0,behavior:"smooth"});else{const s=b.querySelector(".photo-card");if(s){const o=s.getBoundingClientRect().height||200;b.scrollHeight>window.innerHeight&&window.scrollBy({top:o*2,behavior:"smooth"})}}const n=Math.ceil(c/15);l<n?(l+=1,x()):(g(),a.info({title:"Кінець колекції",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(e){console.error("Помилка запиту:",e),a.error({title:"Помилка",message:"Не вдалося завантажити зображення. Спробуйте пізніше.",position:"topRight"})}finally{R(),y=!1}}L.addEventListener("submit",async t=>{t.preventDefault();const e=w.value.trim();if(!e){a.error({title:"Помилка",message:"Будь ласка, введіть пошуковий запит.",position:"topRight"});return}v=e,l=1,c=0,f(),await S(!0),w.value=""});G.addEventListener("click",async()=>{console.log("Кнопка Load More натиснута"),await S(!1)});
//# sourceMappingURL=index.js.map
