import{a as $,S as M,i as a}from"./assets/vendor-CrlV4O_2.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const B="50290691-d51719558e36c91c48babc26d",H="https://pixabay.com/api/",E=15;async function x(o,e=1){console.log("Виклик функції getImagesByQuery із запитом:",o,e);const n={key:B,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:E,page:e};try{return(await $.get(H,{params:n})).data}catch(s){throw s}}const f=document.querySelector(".gallery"),p=document.querySelector(".select");document.querySelector(".loader");let h=null;function G(o){console.log("Виклик createGallery. Масив зображень:",o);try{const e=o.map(({webformatURL:n,largeImageURL:s,tags:t,likes:r,views:i,comments:q,downloads:P})=>(console.log("Обробка зображення:",{webformatURL:n,largeImageURL:s,tags:t}),`
        <li class="gallery-item">
          <a href="${s}" class="gallery-link">
          <img src="${n}" alt="${t}" loading="lazy" />
          </a>
        <div class="info">
        <p><b>Likes:</b> ${r}</p>
        <p><b>Views:</b> ${i}</p>
        <p><b>Comments:</b> ${q}</p>
        <p><b>Downloads:</b> ${P}</p>
      </div>
    </li>`)).join("");f.insertAdjacentHTML("beforeend",e),h?h.refresh():h=new M(".gallery a",{captionsData:"alt",captionDelay:250}),f.children.length>0&&p.classList.remove("is-hidden")}catch(e){throw console.error("Помилка у createGallery:",e),e}}async function g(){try{f.innerHTML="",await d(),console.log("Галерея очищена.")}catch(o){throw console.error("Помилка у функції clearGallery:",o),new Error("Не вдалося очистити галерею.")}}async function O(){try{p.classList.remove("is-hidden")}catch(o){throw console.error("Помилка при показі кнопки Load more:",o),o}}async function d(){try{p.classList.add("is-hidden")}catch(o){throw console.error("Помилка при приховуванні кнопки Load more:",o),o}}const L=document.querySelector(".form"),m=L.querySelector('input[name="search-text"]'),y=document.querySelector(".loader"),R=document.querySelector(".select"),w=document.querySelector(".gallery");let v="",l=1,c=0,u=!1;function A(){y&&(y.style.display="block"),console.log('Loader показано: видимість встановлена на "block".')}function b(){y&&(y.style.display="none"),console.log('Loader сховано: видимість встановлена на "none".')}async function T(o){return new Promise(e=>setTimeout(e,o))}async function S(o=!1){if(u){console.log("Запит уже виконується, новий запит не запускається.");return}u=!0,console.log("Початок завантаження зображень."),A(),d();try{await T(2e3);const e=await x(v,l);if(!e.hits||e.hits.length===0){g(),a.info({title:"Нічого не знайдено",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),d(),b(),u=!1;return}if(o){g(),c=e.totalHits;const s=Math.ceil(c/15);a.success({title:"Успіх",message:`Знайдено ${c} зображень.`,position:"topRight",timeout:2e3})}if(G(e.hits),o)window.scrollTo({top:0,behavior:"smooth"});else{const s=w.querySelector(".photo-card");if(s){const t=s.getBoundingClientRect().height||200;w.scrollHeight>window.innerHeight&&window.scrollBy({top:t*2,behavior:"smooth"})}}const n=Math.ceil(c/15);console.log(`Поточна сторінка: ${l} / ${n}`),l>=n?(a.info({title:"Кінець колекції",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),d()):(l+=1,O())}catch(e){console.error("Помилка запиту:",e),a.error({title:"Помилка",message:"Не вдалося завантажити зображення. Спробуйте пізніше.",position:"topRight"})}finally{b(),u=!1}}L.addEventListener("submit",async o=>{o.preventDefault();const e=m.value.trim();if(!e){a.error({title:"Помилка",message:"Будь ласка, введіть пошуковий запит.",position:"topRight"});return}v=e,l=1,c=0,g(),await S(!0),m.value=""});R.addEventListener("click",async()=>{console.log("Кнопка Load More натиснута"),await S(!1)});
//# sourceMappingURL=index.js.map
