import{a as v,S as P,i}from"./assets/vendor-CrlV4O_2.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))s(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function l(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(o){if(o.ep)return;o.ep=!0;const r=l(o);fetch(o.href,r)}})();const M="50290691-d51719558e36c91c48babc26d",B="https://pixabay.com/api/",E=15;async function H(t,e=1){console.log("Виклик функції getImagesByQuery із запитом:",t,e);const l={key:M,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:E,page:e};try{return(await v.get(B,{params:l})).data}catch(s){throw s}}const h=document.querySelector(".gallery"),d=document.querySelector(".select"),y=document.querySelector(".loader");console.log("Контейнер галереї знайдено:",h);let g=null;function $(t){console.log("Виклик createGallery. Масив зображень:",t);try{const e=t.map(({webformatURL:l,largeImageURL:s,tags:o,likes:r,views:n,comments:S,downloads:q})=>(console.log("Обробка зображення:",{webformatURL:l,largeImageURL:s,tags:o}),`
   <li class="photo-card gallery-item">
     <a href="${s}" class="gallery-link">
     <img src="${l}" alt="${o}" loading="lazy" />
     </a>
   <div class="info">
    <p><b>Likes:</b> ${r}</p>
      <p><b>Views:</b> ${n}</p>
      <p><b>Comments:</b> ${S}</p>
      <p><b>Downloads:</b> ${q}</p>
    </div>
  </li>`)).join("");h.insertAdjacentHTML("beforeend",e),g?g.refresh():g=new P(".gallery a",{captionsData:"alt",captionDelay:250})}catch(e){throw console.error("Помилка у createGallery:",e),e}}function m(){try{h.innerHTML="",console.log("Галерея очищена.")}catch(t){throw console.error("Помилка у функції clearGallery:",t),new Error("Не вдалося очистити галерею.")}}function A(){y&&(y.style.display="block"),console.log("Індикатор завантаження показано.")}function G(){y&&(y.style.display="none"),console.log("Індикатор завантаження сховано.")}function x(){d&&d.classList.remove("is-hidden"),console.log('Кнопку "Load More" показано.')}function O(){d&&d.classList.add("is-hidden"),console.log('Кнопку "Load More" сховано.')}const w=document.querySelector(".form"),p=w.querySelector('input[name="search-text"]');document.querySelector(".loader");const R=document.querySelector(".select"),a=document.querySelector(".gallery");let b="",c=1,u=0,f=!1;async function I(t){return new Promise(e=>setTimeout(e,t))}async function L(t=!1){if(f){console.log("Запит уже виконується, новий запит не запускається.");return}f=!0,A(),O();try{await I(2e3);const e=await H(b,c);if(!e||!Array.isArray(e.hits))throw new Error("Невалідна структура відповіді API");if(e.hits.length===0){i.info({title:"Нічого не знайдено",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}t&&(m(),u=e.totalHits,i.success({title:"Успіх",message:`Знайдено ${u} зображень.`,position:"topRight"})),console.log("Дані, які передаються в createGallery:",e.hits),$(e.hits),console.log("Додані зображення:",e.hits),console.log("Елемент .photo-card:",a.querySelector(".photo-card"));const l=a.querySelector(".photo-card");if(console.log("Елемент .photo-card:",a.querySelector(".photo-card")),l){console.log("Перевірка: блок виконується");const o=l.getBoundingClientRect().height||200;console.log(o),t?window.scrollTo({top:0,behavior:"smooth"}):a.scrollHeight>window.innerHeight&&window.scrollBy({top:o*2,behavior:"smooth"})}const s=Math.ceil(u/15);c<s?(c+=1,x()):i.info({title:"Кінець колекції",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(e){console.error("Помилка запиту:",e),i.error({title:"Помилка",message:"Не вдалося завантажити зображення. Спробуйте пізніше.",position:"topRight"})}finally{G(),f=!1}}w.addEventListener("submit",async t=>{t.preventDefault();const e=p.value.trim();if(!e){i.error({title:"Помилка",message:"Будь ласка, введіть пошуковий запит.",position:"topRight"});return}b=e,c=1,u=0,m(),await L(!0),p.value=""});R.addEventListener("click",async()=>{console.log("Кнопка Load More натиснута"),await L(!1)});
//# sourceMappingURL=index.js.map
